version: "3.9"

services:
  web:
    build: .
    container_name: socialnetwork_api
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://admin:secret@db:5432/redsocial
      - JWT_SECRET_KEY=supersecretkey
    depends_on:
      - db
    volumes:
      - .:/app  

  db:
    image: postgres:16
    container_name: socialnetwork_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=redsocial
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
